import { Category, Service, Testimonial, Platform, ServiceType } from '@/types';

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'TikTok',
    nameAr: 'تيك توك',
    slug: 'tiktok',
    platform: 'tiktok',
    icon: 'tiktok',
    description: 'Boost your TikTok presence',
    descriptionAr: 'عزز حضورك على تيك توك',
    servicesCount: 24,
    order: 1,
    enabled: true,
  },
  {
    id: 'cat-2',
    name: 'Instagram',
    nameAr: 'انستقرام',
    slug: 'instagram',
    platform: 'instagram',
    icon: 'instagram',
    description: 'Grow your Instagram following',
    descriptionAr: 'نمّي متابعيك على انستقرام',
    servicesCount: 32,
    order: 2,
    enabled: true,
  },
  {
    id: 'cat-3',
    name: 'YouTube',
    nameAr: 'يوتيوب',
    slug: 'youtube',
    platform: 'youtube',
    icon: 'youtube',
    description: 'Increase your YouTube views',
    descriptionAr: 'زد مشاهداتك على يوتيوب',
    servicesCount: 18,
    order: 3,
    enabled: true,
  },
  {
    id: 'cat-4',
    name: 'Snapchat',
    nameAr: 'سناب شات',
    slug: 'snapchat',
    platform: 'snapchat',
    icon: 'snapchat',
    description: 'Expand your Snapchat reach',
    descriptionAr: 'وسّع انتشارك على سناب شات',
    servicesCount: 12,
    order: 4,
    enabled: true,
  },
  {
    id: 'cat-5',
    name: 'Twitter/X',
    nameAr: 'تويتر/X',
    slug: 'twitter',
    platform: 'twitter',
    icon: 'twitter',
    description: 'Amplify your tweets',
    descriptionAr: 'ضخّم تغريداتك',
    servicesCount: 15,
    order: 5,
    enabled: true,
  },
  {
    id: 'cat-6',
    name: 'Facebook',
    nameAr: 'فيسبوك',
    slug: 'facebook',
    platform: 'facebook',
    icon: 'facebook',
    description: 'Boost your Facebook page',
    descriptionAr: 'عزز صفحتك على فيسبوك',
    servicesCount: 20,
    order: 6,
    enabled: true,
  },
];

// Mock Services
export const mockServices: Service[] = [
  {
    id: 'srv-1',
    name: 'TikTok Followers - Premium',
    nameAr: 'متابعين تيك توك - بريميوم',
    description: 'High quality TikTok followers with high retention rate. No password required.',
    descriptionAr: 'متابعين تيك توك عالي الجودة مع معدل احتفاظ عالي. لا حاجة لكلمة المرور.',
    platform: 'tiktok',
    type: 'followers',
    categoryId: 'cat-1',
    pricePerThousand: 45,
    minOrder: 100,
    maxOrder: 100000,
    avgTimeMinutes: 60,
    refillSupported: true,
    refillDays: 30,
    rating: 4.8,
    totalOrders: 15420,
    requiredFields: [
      {
        name: 'link',
        label: 'TikTok Profile URL',
        labelAr: 'رابط حساب تيك توك',
        type: 'url',
        placeholder: 'https://tiktok.com/@username',
        placeholderAr: 'https://tiktok.com/@username',
        required: true,
        validation: 'tiktok_profile',
      },
    ],
    startTimeMinutes: 5,
    cancelAllowed: false,
    enabled: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-2',
    name: 'TikTok Likes - Fast Delivery',
    nameAr: 'إعجابات تيك توك - توصيل سريع',
    description: 'Fast delivery TikTok likes for your videos. Start within minutes.',
    descriptionAr: 'إعجابات تيك توك سريعة التوصيل لفيديوهاتك. تبدأ خلال دقائق.',
    platform: 'tiktok',
    type: 'likes',
    categoryId: 'cat-1',
    pricePerThousand: 25,
    minOrder: 50,
    maxOrder: 50000,
    avgTimeMinutes: 30,
    refillSupported: true,
    refillDays: 15,
    rating: 4.9,
    totalOrders: 23150,
    requiredFields: [
      {
        name: 'link',
        label: 'TikTok Video URL',
        labelAr: 'رابط فيديو تيك توك',
        type: 'url',
        placeholder: 'https://tiktok.com/@username/video/...',
        placeholderAr: 'https://tiktok.com/@username/video/...',
        required: true,
        validation: 'tiktok_video',
      },
    ],
    startTimeMinutes: 2,
    cancelAllowed: true,
    enabled: true,
    featured: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-3',
    name: 'TikTok Views - Instant Start',
    nameAr: 'مشاهدات تيك توك - بدء فوري',
    description: 'Instant start TikTok video views. High quality and fast.',
    descriptionAr: 'مشاهدات فيديو تيك توك بدء فوري. جودة عالية وسريعة.',
    platform: 'tiktok',
    type: 'views',
    categoryId: 'cat-1',
    pricePerThousand: 8,
    minOrder: 500,
    maxOrder: 1000000,
    avgTimeMinutes: 15,
    refillSupported: false,
    rating: 4.7,
    totalOrders: 45000,
    requiredFields: [
      {
        name: 'link',
        label: 'TikTok Video URL',
        labelAr: 'رابط فيديو تيك توك',
        type: 'url',
        placeholder: 'https://tiktok.com/@username/video/...',
        placeholderAr: 'https://tiktok.com/@username/video/...',
        required: true,
        validation: 'tiktok_video',
      },
    ],
    startTimeMinutes: 0,
    cancelAllowed: true,
    enabled: true,
    featured: false,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-4',
    name: 'Instagram Followers - Real',
    nameAr: 'متابعين انستقرام - حقيقيين',
    description: 'Real Instagram followers from active accounts. High retention.',
    descriptionAr: 'متابعين انستقرام حقيقيين من حسابات نشطة. احتفاظ عالي.',
    platform: 'instagram',
    type: 'followers',
    categoryId: 'cat-2',
    pricePerThousand: 55,
    minOrder: 100,
    maxOrder: 50000,
    avgTimeMinutes: 120,
    refillSupported: true,
    refillDays: 30,
    rating: 4.6,
    totalOrders: 18320,
    requiredFields: [
      {
        name: 'link',
        label: 'Instagram Profile URL',
        labelAr: 'رابط حساب انستقرام',
        type: 'url',
        placeholder: 'https://instagram.com/username',
        placeholderAr: 'https://instagram.com/username',
        required: true,
        validation: 'instagram_profile',
      },
    ],
    startTimeMinutes: 10,
    cancelAllowed: false,
    enabled: true,
    featured: true,
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-5',
    name: 'Instagram Likes - Premium',
    nameAr: 'إعجابات انستقرام - بريميوم',
    description: 'Premium quality Instagram likes for posts and reels.',
    descriptionAr: 'إعجابات انستقرام عالية الجودة للمنشورات والريلز.',
    platform: 'instagram',
    type: 'likes',
    categoryId: 'cat-2',
    pricePerThousand: 30,
    minOrder: 50,
    maxOrder: 100000,
    avgTimeMinutes: 45,
    refillSupported: true,
    refillDays: 14,
    rating: 4.8,
    totalOrders: 28500,
    requiredFields: [
      {
        name: 'link',
        label: 'Instagram Post URL',
        labelAr: 'رابط منشور انستقرام',
        type: 'url',
        placeholder: 'https://instagram.com/p/...',
        placeholderAr: 'https://instagram.com/p/...',
        required: true,
        validation: 'instagram_post',
      },
    ],
    startTimeMinutes: 5,
    cancelAllowed: true,
    enabled: true,
    featured: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-6',
    name: 'YouTube Views - High Retention',
    nameAr: 'مشاهدات يوتيوب - احتفاظ عالي',
    description: 'High retention YouTube views that count. Safe for monetization.',
    descriptionAr: 'مشاهدات يوتيوب باحتفاظ عالي تُحتسب. آمنة للربح.',
    platform: 'youtube',
    type: 'views',
    categoryId: 'cat-3',
    pricePerThousand: 35,
    minOrder: 1000,
    maxOrder: 500000,
    avgTimeMinutes: 180,
    refillSupported: true,
    refillDays: 30,
    rating: 4.5,
    totalOrders: 12800,
    requiredFields: [
      {
        name: 'link',
        label: 'YouTube Video URL',
        labelAr: 'رابط فيديو يوتيوب',
        type: 'url',
        placeholder: 'https://youtube.com/watch?v=...',
        placeholderAr: 'https://youtube.com/watch?v=...',
        required: true,
        validation: 'youtube_video',
      },
    ],
    startTimeMinutes: 30,
    cancelAllowed: false,
    enabled: true,
    featured: true,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-7',
    name: 'YouTube Subscribers',
    nameAr: 'مشتركين يوتيوب',
    description: 'Real YouTube subscribers for your channel growth.',
    descriptionAr: 'مشتركين يوتيوب حقيقيين لنمو قناتك.',
    platform: 'youtube',
    type: 'followers',
    categoryId: 'cat-3',
    pricePerThousand: 120,
    minOrder: 50,
    maxOrder: 20000,
    avgTimeMinutes: 360,
    refillSupported: true,
    refillDays: 60,
    rating: 4.4,
    totalOrders: 5600,
    requiredFields: [
      {
        name: 'link',
        label: 'YouTube Channel URL',
        labelAr: 'رابط قناة يوتيوب',
        type: 'url',
        placeholder: 'https://youtube.com/@channel',
        placeholderAr: 'https://youtube.com/@channel',
        required: true,
        validation: 'youtube_channel',
      },
    ],
    startTimeMinutes: 60,
    cancelAllowed: false,
    enabled: true,
    featured: false,
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'srv-8',
    name: 'Snapchat Views',
    nameAr: 'مشاهدات سناب شات',
    description: 'Snapchat story and spotlight views.',
    descriptionAr: 'مشاهدات ستوري وسبوتلايت سناب شات.',
    platform: 'snapchat',
    type: 'views',
    categoryId: 'cat-4',
    pricePerThousand: 15,
    minOrder: 100,
    maxOrder: 100000,
    avgTimeMinutes: 30,
    refillSupported: false,
    rating: 4.6,
    totalOrders: 8900,
    requiredFields: [
      {
        name: 'link',
        label: 'Snapchat Username',
        labelAr: 'اسم مستخدم سناب شات',
        type: 'text',
        placeholder: 'username',
        placeholderAr: 'اسم المستخدم',
        required: true,
      },
    ],
    startTimeMinutes: 5,
    cancelAllowed: true,
    enabled: true,
    featured: false,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
];

// Mock Testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: 'dv-store',
    name: 'DV STORE',
    nameAr: 'متجر DV STORE',
    avatar: '/client_ratings/DV_STORE.jpeg',
    rating: 5,
    text: 'I used to do everything manually. After using the platform, it saved me a lot of time and orders started running without me having to follow up on every detail.',
    textAr: 'كنت أشتغل يدوي قبل، وبعد ما استخدمت المنصة وفّرت علي وقت كبير. الطلبات صارت تمشي بدون ما أتابع كل شيء بنفسي',
    platform: 'tiktok',
  },
  {
    id: 'media-click',
    name: 'Media Click',
    nameAr: 'متجر Media Click',
    avatar: '/client_ratings/media_click.jpeg',
    rating: 5,
    text: 'It was easy to use from day one. The Salla integration was clear and everything worked smoothly without complications.',
    textAr: 'استخدمتها بسهولة من أول يوم. الربط مع سلة كان واضح، وكل شيء كان ماشي بدون تعقيد',
    platform: 'facebook',
  },
  {
    id: 'saudi-like',
    name: 'Saudi Like',
    nameAr: 'متجر سعودي لايك',
    avatar: '/client_ratings/saudi_like.jpeg',
    rating: 5,
    text: 'I tried it myself and the difference is clear. The system is organized and fulfillment is faster than expected. Honestly, a comfortable experience.',
    textAr: 'استخدمتها بنفسي، والفرق واضح. النظام مرتب، والتنفيذ أسرع من المتوقع. تجربة مريحة بصراحة',
    platform: 'youtube',
  },
  {
    id: 'blue-10',
    name: 'Blue 10',
    nameAr: 'متجر Blue 10',
    avatar: '/client_ratings/blue_10.png',
    rating: 5,
    text: "We tested the platform under high load and it stayed stable. Orders didn't get stuck, and that's what matters most to us.",
    textAr: 'جربنا المنصة وقت ضغط، وكانت الأمور مستقرة. ما واجهنا تعليق طلبات، وهذا اللي يهمنا أكثر شيء',
    platform: 'tiktok',
  },
  {
    id: 'cloud-box',
    name: 'Cloud Box',
    nameAr: 'متجر Cloud Box',
    avatar: '/client_ratings/cloud_box.png',
    rating: 5,
    text: "I used the platform for a while and everything was clear and smooth. I didn't need to contact support much because the work was running by itself. I honestly rely on it now.",
    textAr: 'استخدمت المنصة فترة، وكل شيء كان واضح وسلس. ما احتجت أرجع للدعم كثير لأن الشغل ماشي من نفسه. صراحة اعتمدتها',
    platform: 'instagram',
  },
];

// Platform configuration
export const platformConfig: Record<Platform, { color: string; bgClass: string; icon: string }> = {
  tiktok: { color: '#ff0050', bgClass: 'badge-tiktok', icon: 'Music' },
  instagram: { color: '#E4405F', bgClass: 'badge-instagram', icon: 'Instagram' },
  youtube: { color: '#FF0000', bgClass: 'badge-youtube', icon: 'Youtube' },
  snapchat: { color: '#FFFC00', bgClass: 'badge-snapchat', icon: 'Ghost' },
  twitter: { color: '#1DA1F2', bgClass: 'badge-twitter', icon: 'Twitter' },
  facebook: { color: '#1877F2', bgClass: 'badge-facebook', icon: 'Facebook' },
};

export const serviceTypeIcons: Record<ServiceType, string> = {
  followers: 'Users',
  likes: 'Heart',
  views: 'Eye',
  comments: 'MessageCircle',
  shares: 'Share2',
  saves: 'Bookmark',
};
